name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:


jobs:
    build_and_test_windows:
      name: Windows Test Redis Version
      runs-on: windows-latest
      strategy:
        fail-fast: false
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - uses: Vampire/setup-wsl@v2
          with:
            distribution: Ubuntu-22.04
        - name: Install Redis
          shell: wsl-bash {0}
          run: |
            sudo apt-get update
            sudo apt-get install curl gpg lsb-release libgomp1 jq -y
            curl https://packages.redis.io/redis-stack/redis-stack-server-7.4.0-v2.jammy.x86_64.tar.gz -o redis-stack.tar.gz
            tar xf redis-stack.tar.gz
        - name: Run redis-server
          shell: wsl-bash {0}
          working-directory: ./tests/RedisConfigs
          run: |
            pwd
            ls .
            mkdir -p ../Temp
            cat ./Basic/primary-6379-3.0.conf
            # .\redis-server.exe --service-install --service-name "redis-6379" "..\Basic\primary-6379-3.0.conf"
            # .\redis-server.exe --service-install --service-name "redis-6380" "..\Basic\replica-6380.conf"
            ../../redis-stack-server-7.4.0-v2/bin/redis-stack-server ./Basic/primary-6379-3.0.conf &
            sleep 3
            ../../redis-stack-server-7.4.0-v2/bin/redis-cli INFO SERVER | grep redis_version
